plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/*_schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "storage/**/*"

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 180

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "config/environments/*.rb"
    - "config/initializers/*.rb"
    - "spec/**/*"

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: strict

Rails/InverseOf:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 7
